[package]
name = "wsl_open_browser"
version = "0.1.0"
authors = ["Luciano Bestia <LucianoBestia@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unwrap="1.2.1"

